### ISSUE TITLE
Support for inline document data

### ISSUE THREAD

**Issue by pabluk** [Antojitos/chalupas#10]
I would like to build a Markdown online editor to convert markdown to html on the fly, but the API only supports file uploads https://github.com/Antojitos/chalupas/blob/master/chalupas/routes.py#L19 and I can't create files using javascript (client side) via a textarea field :disappointed:

It would be great to have an optional field for `document` (as `from` and `to`) to send inline data to be converted.

**Comment by amessinger** [comment]
Sure thing. Next feature to be implemented then!
